name: Node.js Release 

on:
  workflow_dispatch:
 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git config --global user.name "GitHub Action CI"
    - run: git config --global user.email "user@example.org"
    - run: npm install
    - run: npx @grafana/toolkit plugin:sign
      env:
        GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
    - run: npm run release -- patch --ci -VV
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: cloudspout-button-panel.zip
        path: cloudspout-button-panel.zip
